name: Build Next.js Application
on: [push]
jobs:
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project
    permissions: write-all
    steps:
      - name: Download site content
        uses: actions/download-artifact@v4
        with:
          name: static-site
      - name: View content
        run: ls -R
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      # - uses: actions/checkout@v4
      # - name: Create release
      #   uses: elgohr/Github-Release-Action@v5
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     title: Release ${{ github.run_number }}
      - name: Create release
        # uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        run: echo ${{github.ref}}

  build-project:
    name: Building Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install modules
        run: npm i
      - name: Build project
        run: npm run build
      - name: upload static site
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: .next/
