name: Build Next.js Application
on: push
jobs:
  build-project:
    name: Building Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install modules
        run: npm i
      - name: Build project
        run: npm run build
      - name: upload static site
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: .next/
