name: Build Next.js Application
on: push
jobs:
  build-next.js:
    name: Building Next.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install modules
        uses: npm i
      - name: Build project
        uses: npm run build
